import Head from "next/head";

export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2">
      <Head>
        <title>Tailwindcss</title>
      </Head>

      <div className="flex w-screen">
        <div className="bg-purple-900 w-1/2 h-screen flex items-center justify-center">
          <div className="border-8 border-black bg-gray-100 rounded-3xl w-64 h-5/6 absolute">
            <div className="flex justify-center relative">
              <span className="w-36 h-5 bg-black rounded-3xl absolute -top-2"></span>
            </div>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-6 w-6 relative left-48 top-5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z"
              />
            </svg>
            <div className="px-4 py-10">
              <span className="uppercase text-xs font-thin text-purple-900">
                product new
              </span>
              <h1 className="text-3xl mt-1 font-serif text-purple-900">
                Fast, automatic and intuitive to use software
              </h1>
              <div className="flex items-end text-purple-900">
                <span className="text-8xl font-serif font-italic">95</span>
                <span className="text-4xl font-serif">%</span>
              </div>
              <p className="text-gray-700 text-sm font-sans pt-6">
                The utility of synthetic data generated by the Synthesized
                software for a typical machine learning task compared to
                original data.
              </p>
              <div className="flex items-center justify-center mt-5">
              <button className="bg-pink-400 py-2 px-8 rounded-3xl">
                <span className="text-white font-sans font-semibold"> Explore the docs </span>
              </button>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-purple-100 w-1/2 h-screen"></div>
      </div>
    </div>
  );
}
